# =========================================================
# ECOINVENTORY PRO - SUPABASE (POSTGRESQL)
# =========================================================

spring.application.name=EcoInventoryPro

# =========================================================
# SERVIDOR
# =========================================================

server.port=8080


# =========================================================
# BASE DE DATOS SUPABASE
# USANDO SESSION POOLER (IPv4)
# =========================================================

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qbggqllmwmbpctvgatcj
spring.datasource.password=VRQJxXw8VYIsrkBd
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# LOGGING
# =========================================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE